### ISSUE TITLE
Doesn't download any receipts

### ISSUE THREAD

**Issue by khoslaventures** [ridereceipts/ridereceipts#15]
**Describe the bug**
I've downloaded the app and also ran from source and am unable to download any receipts!

**To Reproduce**
1. Run Ride Receipts
2. Login with Credentials
3. Select any of the options for downloading receipts
4. Stuck on the download page, no visible progress. Folder in Documents is empty.

**Expected behavior**
I should be seeing a progress bar for any downloads, and files in the directory inside Documents folder. I've waited 5 hours for my receipts of the previous year, and 3 hours on all the other options.

**Screenshots**
![image](https://user-images.githubusercontent.com/8366960/45620967-7bec9200-ba33-11e8-87d6-b37d9e48a7fa.png)

**Desktop (please complete the following information):**
 - OS: MacOS High Sierra 10.13.6

**Additional context**
How long does it normally take to download 31 receipts? How about 321? No progress has been made on my end, and not sure why. Does this still work?

**Comment by mrgodhani** [comment]
@khoslaventures  is this the latest version of the App ? It should work. Sometimes you might have to re run the app or try it out to figure what is happening by clicking on `Application` > `Debug` before you click on `Uber` option. With their new rebranded UI I have seen cases where their servers goes down and gives "Internal server error"

**Comment by mrgodhani** [comment]
<img width="1072" alt="screen shot 2018-09-17 at 8 51 02 am" src="https://user-images.githubusercontent.com/1529009/45623954-e662f980-ba56-11e8-8ab8-003aa04cf27e.png">
Otherwise just tried right now works fine

**Comment by khoslaventures** [comment]
Yea, this is the latest version of the app.

So I went into debug mode. Managed to login, selected the receipts from the past year.

![image](https://user-images.githubusercontent.com/8366960/45660044-ee995400-baab-11e8-8792-6941c98c5ea2.png)

It just sits here on very first trip it opens. Any ideas?

**Comment by khoslaventures** [comment]
Also, as a side note, would it be possible to get stuff before a year ago by having screenshots taken of each trip page? Or maybe I could write that logic myself, any ideas where to start?

**Comment by mrgodhani** [comment]
That explains why. I don't see "Save Invoice" option.

<img width="467" alt="screen shot 2018-09-17 at 10 05 11 pm" src="https://user-images.githubusercontent.com/1529009/45660245-c9b1da80-bac5-11e8-92a7-4218260b189b.png">

**Comment by mrgodhani** [comment]
> Also, as a side note, would it be possible to get stuff before a year ago by having screenshots taken of each trip page? Or maybe I could write that logic myself, any ideas where to start?

That feature we are bringing in pro version. Where you can just select custom date range. Now looking at your situation I would need to modify some code so it still takes screenshot.

**Comment by mrgodhani** [comment]
Should be fixed now in this release https://github.com/ridereceipts/ridereceipts/releases/tag/v1.6.4

**Comment by khoslaventures** [comment]
Hmm I tried it, and my progress bar still doesn't move. Not sure what's happening.

**Comment by mrgodhani** [comment]
Difficult to test because US have no invoices.  Eventually code here https://github.com/ridereceipts/ridereceipts/blob/50142cab11bcb26b0eae0ef10dc9389177f819da/src/renderer/services/puppeteer_uberv2.js#L342 suppose to check if that element is there or not depending on that still should move on

**Comment by khoslaventures** [comment]
Ok, I'll try commenting out those lines and see if I can just get screenshots of the receipts instead. That would suffice for me personally. I'll let you know how it goes.

**Comment by mrgodhani** [comment]
@khoslaventures I would say best way is to debug using console.log. if `invoiceButton` is false it should still move ahead. Also console errors would be helpful

**Comment by khoslaventures** [comment]
I set `invoiceButton` to false. Still no luck. Progress bar doesn't move forward at all. 

I noticed this error though in my console:
```
/Users/akashkhosla/ridereceipts/node_modules/puppeteer/lib/FrameManager.js:862 Uncaught (in promise) TimeoutError: waiting for selector "#root > div > div > div > div > div:nth-child(1) > div > div > div:nth-child(2) > div span" failed: timeout 30000ms exceeded
    at new WaitTask (/Users/akashkhosla/ridereceipts/node_modules/puppeteer/lib/FrameManager.js:862:28)
    at Frame._waitForSelectorOrXPath (/Users/akashkhosla/ridereceipts/node_modules/puppeteer/lib/FrameManager.js:753:12)
    at Frame.waitForSelector (/Users/akashkhosla/ridereceipts/node_modules/puppeteer/lib/FrameManager.js:711:17)
    at Page.waitForSelector (/Users/akashkhosla/ridereceipts/node_modules/puppeteer/lib/Page.js:1043:29)
    at _callee6$ (webpack-internal:///./src/renderer/services/puppeteer_uberv2.js:644:23)
    at tryCatch (webpack-internal:///./node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (webpack-internal:///./node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (webpack-internal:///./node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (webpack-internal:///./node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at eval (webpack-internal:///./node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13)
```

**Comment by mrgodhani** [comment]
@khoslaventures I found that most recently page doesn't open when browser is hidden/headless. But it works when `debug` config is on

**Comment by khoslaventures** [comment]
Hmm I see. Yea I have this open in debug mode. It loads the first receipts and just sits there on the first one. Still have `invoiceButton` set to false.

```
/Users/akashkhosla/ridereceipts/node_modules/puppeteer/lib/FrameManager.js:862 Uncaught (in promise) TimeoutError: waiting for selector "#root > div > div > div > div > div:nth-child(1) > div > div > div:nth-child(2) > div span" failed: timeout 30000ms exceeded
    at new WaitTask (/Users/akashkhosla/ridereceipts/node_modules/puppeteer/lib/FrameManager.js:862:28)
    at Frame._waitForSelectorOrXPath (/Users/akashkhosla/ridereceipts/node_modules/puppeteer/lib/FrameManager.js:753:12)
    at Frame.waitForSelector (/Users/akashkhosla/ridereceipts/node_modules/puppeteer/lib/FrameManager.js:711:17)
    at Page.waitForSelector (/Users/akashkhosla/ridereceipts/node_modules/puppeteer/lib/Page.js:1043:29)
    at _callee6$ (webpack-internal:///./src/renderer/services/puppeteer_uberv2.js:644:23)
    at tryCatch (webpack-internal:///./node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (webpack-internal:///./node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (webpack-internal:///./node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (webpack-internal:///./node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at eval (webpack-internal:///./node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13)
```

This was the most recent console error when in debug mode and the page was loaded.

**Comment by khoslaventures** [comment]
So my page is loading. I commented out:
```
// await page.waitForSelector('#root > div > div > div > div > div:nth-child(1) > div > div > div:nth-child(2) > div span')
```
And it works. Now what this is telling me is that for some reason, this element is not being detected. Is that because it points to the Download button which is non-existent?

**Comment by nunocordeiro** [comment]
I'm having the same (or similar) issue on Windows 10. Has this been fixed or should I attempt to make a build with the same workaround that khoslaventures used?

Thanks!

**Comment by mrgodhani** [comment]
@nunocordeiro that mechanism is removed in new version of the app. New version of the app now downloads receipts from gmail account.

**Comment by nunocordeiro** [comment]
It's not working for me, possibly because I don't have direct links to my invoices from the email.
I tried one of the old versions, but even though the links are there, it doesn't download them - something must've changed in the way chrome handles your scripting.

Should I open a new issue for you? What information can I provide you with?

**Comment by mrgodhani** [comment]
@nunocordeiro if you dont have any emails in account then it wont download.  Old versions use to download from dashboard which have removed in newer version. That would be supported only on pro that is coming soon in New year and would be a paid app.  You can create new issue if you still find that it is not downloading receipts from your gmail account and you believe you have email receipts.

**Comment by nunocordeiro** [comment]
Done!
